### ISSUE TITLE
Ability to expose Grafana over 2 subnets

### ISSUE THREAD

**Issue by ggouzi** [canonical/cos-lite-bundle#128]
### Enhancement Proposal

# Description

Add the ability to expose Grafana over 2 subnets/IPs

# Context

We are deploying COS which will be accessible by Canonical internal team but will also be accessible by customer.
The subnet used by Canonical is completely segregated from the other subnets.
Therefore, canonical internal team can only access COS from one subnet (10.46.16.0/24), which is not accessible from customer's team. And vice-versa, customer needs to access COS (read-only) over a subnet which is not accessible from Canonical (10.46.27.0/24).

# Workaround

Create a LoadBalancer using kubectl and expose traefik traffic over an external IP address consumed from customer's subnet.

```
kubectl --kubeconfig=cos-kubeconfig apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: traefik-customer-facing
  namespace: cos
spec:
  type: LoadBalancer
  loadBalancerIP: 10.46.27.98 # Need to match k8s load-balancer-cidrs https://charmhub.io/k8s/configurations#load-balancer-cidrs
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: traefik
  - protocol: TCP
    port: 443
    targetPort: 443
    name: traefik-tls
  selector:
    app.kubernetes.io/name: traefik
EOF
```

This workaround works and Grafana endpoint is accessible from both IP addresses 10.46.16.98 and 10.46.17.98.

![Image](https://github.com/user-attachments/assets/e22fb8eb-76ec-42c6-8ba3-ae4617a27b6c)

However, this workaround is not suitable, as it is not managed by Juju.
