### ISSUE TITLE
Incorrect command for fetching/organizing endpoints

### ISSUE THREAD

**Issue by YHatahet** [canonical/cos-lite-bundle#89]
I am using Juju v3.1.6
In this page under the ["Browse dashboards" section](https://charmhub.io/topics/canonical-observability-stack/tutorials/install-microk8s#heading--browse-dashboards), the command listed did not work for me:
```
juju run traefik/0 show-proxied-endpoints | yq '."unit-traefik-0".results."proxied-endpoints"' | jq
```
Instead, I modified and produced the intended result using the following command:
```
juju run traefik/0 show-proxied-endpoints | yq '."proxied-endpoints"' | jq
```

**Comment by sed-i** [comment]
Thanks for letting us know!
Indeed, the output format for `juju run` (juju 3) is different from `juju run-action` (2.9).
While currently juju readily outputs valid yaml, it is probably less brittle to always supply `--format`:

```
j run trfk/0 show-proxied-endpoints --format yaml                    
Running operation 9 with 1 task
  - task 10 on unit-trfk-0

Waiting for task 10...
trfk/0: 
  id: "10"
  results: 
    proxied-endpoints: '{"am": {"url": "http://10.43.8.206/trfk-am"}}'
    return-code: 0
  status: completed
  timing: 
    completed: 2023-12-15 13:11:29 -0500 EST
    enqueued: 2023-12-15 13:11:28 -0500 EST
    started: 2023-12-15 13:11:28 -0500 EST
  unit: trfk/0
```

In which case, you'd need to query as follows:
```
j run trfk/0 show-proxied-endpoints --format yaml | yq '."trfk/0".results."proxied-endpoints"' | jq 
Running operation 17 with 1 task
  - task 18 on unit-trfk-0

Waiting for task 18...
{
  "am": {
    "url": "http://10.43.8.206/trfk-am"
  }
}
```

Doc updated, thank you!
